version: '3.1'

networks:
  traefik-network:
    external: true

services:

  entrypoint:
    image: emilevauge/whoami
    networks:
      - traefik-network
    deploy:
      labels:
        - "traefik.docker.network=traefik-network"
        - "traefik.port=80"
        - "traefik.frontend.rule=Host:media-dl.ab0.fr"

  sonarr:
    image: linuxserver/sonarr
    networks:
      - traefik-network
    environment:
      PUID: 9000
      PGID: 9000
      TZ: Europe/Paris
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/var/swarm-data/config/media-dl/sonarr/:/config/"
      - "/var/download-data/TV:/tv"
      - "/var/download-data/work/nzbget:/downloads"
    deploy:
      labels:
        - "traefik.docker.network=traefik-network"
        - "traefik.port=8989"
        - "traefik.frontend.rule=Host:media-dl.ab0.fr;PathPrefix:/sonarr"

  torrent:
    image: linuxserver/rutorrent
    networks:
      - traefik-network
    environment:
      PUID: 9000
      PGID: 9000
      TZ: Europe/Paris
    volumes:
      - "/var/swarm-data/config/media-dl/torrent/nginx/:/config/nginx/"
      - "/var/swarm-data/config/media-dl/torrent/php/php.ini:/config/php/php.ini"
      - "/var/swarm-data/config/media-dl/torrent/rtorrent/rtorrent.rc:/config/rtorrent/rtorrent.rc"
      - "/var/swarm-data/config/media-dl/torrent/rutorrent/settings/config.php:/config/rutorrent/settings/config.php"
      - "/var/download-data/work/torrent/:/downloads/"
    ports:
      - "5000:5000"
      - "51413:51413"
      - "6881:6881/udp"
    deploy:
      labels:
        - "traefik.port=80"
        - "traefik.docker.network=traefik-network"
        - "traefik.frontend.rule=Host:media-dl.ab0.fr;PathPrefixStrip:/torrent"

  nzbget:
    image: linuxserver/nzbget
    networks:
      - traefik-network
    environment:
      PUID: 9000
      PGID: 9000
      TZ: Europe/Paris
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/var/download-data/work/nzbget/:/downloads/"
      - "/var/swarm-data/config/media-dl/nzbget/:/config/"
    deploy:
      labels:
        - "traefik.docker.network=traefik-network"
        - "traefik.port=6789"
        - "traefik.frontend.rule=Host:media-dl.ab0.fr;PathPrefixStrip:/nzbget/"
