- hosts: docker
  remote_user: root
  become: yes
  become_user: docker
  vars_files:
    - secrets.yml
  tasks:
    - name: Necessary folders
      file:
        path: "{{item}}"
        state: directory
      with_items:
        - ~/stacks
        - /var/swarm-data/config/media-dl/sonarr
        - /var/swarm-data/config/media-dl/radarr
        - /var/swarm-data/config/media-dl/nzbget
        - /var/swarm-data/config/media-dl/torrent
        - /var/download-data/work/completed # completed nzb
        - /var/download-data/work/incoming # torrent dl dir
        - /var/download-data/work/watched # watchdir for torrent files
        - /var/download-data/TV
        - /var/download-data/Movies
    - name: Copy config files
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        force: no
      with_items:
        - { src: ./config/sonarr.xml, dest: /var/swarm-data/config/media-dl/sonarr/config.xml }
        - { src: ./config/radarr.xml, dest: /var/swarm-data/config/media-dl/radarr/config.xml }
        - { src: ./config/nzbget.conf, dest: /var/swarm-data/config/media-dl/nzbget/nzbget.conf }
        - { src: ./config/torrent/, dest: /var/swarm-data/config/media-dl/torrent/ }
    - name: Copy entrypoint app
      copy:
        src: ./entrypoint/
        dest: /var/swarm-data/media-dl/entrypoint-app/
    - name: Copy stack file
      template:
        src: ./media-dl.yml.j2
        dest: ~/stacks/media-dl.yml
    - name: Stack deployment
      command: docker stack deploy -c ~/stacks/media-dl.yml media-dl
