- hosts: docker
  remote_user: root
  become: yes
  become_user: docker
  vars_files:
    - secrets.yml
  tasks:
    - name: Necessary folders
      file:
        path: "{{item}}"
        state: directory
      with_items:
        - ~/stacks
    - name: Copy stack file
      copy:
        src: ./media-dl.yml
        dest: ~/stacks/media-dl.yml
    - name: Stack deployment
      command: docker stack deploy -c ~/stacks/media-dl.yml media-dl
